' (C) Crown copyright 2024 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

@startuml

!include look.iuml

!include coupling/coupling_mod.iuml
!include coupling/coupler_exchange_2d_mod.iuml

abstract_external_field_mod::abstract_external_field_type <|-- coupler_exchange_2d_mod::coupler_exchange_2d_type

@enduml
