' (C) Crown copyright 2025 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

class id_logical_pair_mod::id_logical_pair_type {
  -bool_flag_: logical

  +initialise( <<in>> bool_flag: logical, <<in>> id: logical ) :
  +get_logical( ) : logical
}
